title: Jason N. Gaylord
subtitle: <i class="fas fa-code-simple"></i> Coder from Northeast PA
author: Jason N. Gaylord
description: >
  Jason Gaylord is a web application developer from Northeast Pennsylvania. He is the AVP of Technology for biBERK and also a Co-Organizer for TechBash.
baseurl: 
url: "https://www.jasongaylord.com"

# git edit capabilities
remote_theme: jasongaylord/SpaacedOut
git:
  owner: jasongaylord
  repository: JasonGaylord.com
  branch: master

# pagination and permalink
show_excerpts: true
paginate: 10
page_group_size: 5
paginate_path: "/blog/page/:num"
permalink: /blog/:year/:month/:day/:title

# content expansion
content:
  head-s: true
  header-s: true
#  header-suffix: header-suffix.html
#  head-suffix: head-suffix.html  

# contact
contact: 
  avatar-image: https://cdn.jasongaylord.com/images/site/jason.png
#  email: email@gmail.com # Uncomment if you want feedback via email (it will expose your email)
#  url: https://domain.com/contact.html # Uncomment if you want to provide a contact form

# social links (uncomment the links you'd like to include and)
social:
  name: Jason Gaylord
  facebook: jason.gaylord
  github: jasongaylord
  instagram: jason.gaylord
  linkedin: jasongaylord
  mastodonUser: jasongaylord
  mastodonServer: techhub.social
  twitter: jgaylord
#  pinterest: jekyll
#  stackoverflow: "11111"
#  youtube: jekyll
  links: 
    - https://twitter.com/jgaylord
    - https://www.facebook.com/jason.gaylord
    - https://www.linkedin.com/in/jasongaylord
    - https://github.com/jasongaylord

google:
  analytics: UA-2053573-1
  adsense: ca-pub-2663334448189019
 
rss: rss
# The site generates a feed at /feed.xml. Uncomment below to override
feed:
  path: /feed.xml


# jekyll seo formatting
twitter:
  username: jgaylord
  card: summary_large_image

webmaster_verifications:
  google: cjbVriPAfj0T_WG2hUu3GJTxRjCnWCZ6veDMczcUEHg

# comments
comments:
  enabled: true
  show_count: false
  disqus_shortname: jasongaylord

# front matter
defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: post
      comments: true
  -
    scope:
      path: "pages"
      type: "pages"
    values:
      layout: page
      comments: false
  -
    scope:
      path: "assets/pages"
      type: "pages"
    values:
      layout: page
      comments: false

#Kramdown Configuration      
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

#Plugins and configuration
future: false
timezone: America/New_York
plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap