title: My site
subtitle: Just some words
author: George Washington
description: >
  Here is my website. This description will appear in the meta
  data on the site and in the feed.xml site description.

# git edit capabilities
git:
#  host: https://github.com/
  repository: jasongaylord/SpaacedOut
  branch: gh-pages

# pagination and permalink
show_excerpts: true
paginate: 5
page_group_size: 5
paginate_path: "/blog/page/:num"
permalink: /blog/:year/:month/:day/:title

# content expansion
content:
#  head-suffix: head-suffix.html  
#  header-suffix: header-suffix.html

# contact
contact: 
  avatar-image: /assets/images/avatar.png
#  email: email@gmail.com # Uncomment if you want feedback via email (it will expose your email)
#  url: https://domain.com/contact.html # Uncomment if you want to provide a contact form

# social links (uncomment the links you'd like to include and)
social:
#  facebook: jekyll
#  github: jekyll
#  instagram: jekyll
#  linkedin: jekyll
#  pinterest: jekyll
#  stackoverflow: "11111"
#  twitter: jekyllrb
#  youtube: jekyll

#  google_analytics: UA-NNNNNNNN-N

rss: rss
# The site generates a feed at /feed.xml. Uncomment below to override
# feed:
#   path: /myfeed.xml

# comments
comments:
#  enabled: false
#  show_count: false
#  disqus_shortname: jekyll

# front matter
defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: post
      comments: true
  -
    scope:
      path: "pages"
      type: "pages"
    values:
      layout: page
      comments: false
  -
    scope:
      path: "assets/pages"
      type: "pages"
    values:
      layout: page
      comments: false

plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap